// SPDX-License-Identifier: MIT
//
// Session-table (fake PFCP) loader tests: format handling, hex TEIDs, and the
// requirement that one malformed row cannot take the pipeline down.
#include "gtpm/session.hpp"

#include <unistd.h>

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>

#include "test_harness.hpp"

using namespace gtpm;

namespace {

/// mkstemp rather than tmpnam: the deprecated call races and the compiler is
/// right to complain about it.
std::string write_temp(const std::string& contents) {
  char tmpl[] = "/tmp/gtpm-sessions-XXXXXX";
  const int fd = ::mkstemp(tmpl);
  if (fd >= 0) ::close(fd);
  const std::string path(tmpl);
  std::ofstream out(path, std::ios::trunc);
  out << contents;
  return path;
}

}  // namespace

TEST("session/loads_well_formed_csv") {
  const std::string path = write_temp(
      "imsi,ul_teid,dl_teid,rating_group,msisdn,apn\n"
      "310150000000001,100,200,10,15551234567,internet\n"
      "310150000000002,101,201,20,15551234568,ims\n");
  const SessionLoadResult r = load_sessions_csv(path);
  std::remove(path.c_str());

  REQUIRE(r.ok());
  REQUIRE_EQ(r.sessions.size(), size_t{2});
  CHECK_EQ(r.sessions[0].imsi, 310150000000001ULL);
  CHECK_EQ(r.sessions[0].ul_teid, 100u);
  CHECK_EQ(r.sessions[0].dl_teid, 200u);
  CHECK_EQ(r.sessions[0].rating_group, 10u);
  CHECK_EQ(r.sessions[0].msisdn, std::string("15551234567"));
  CHECK_EQ(r.sessions[1].apn, std::string("ims"));
  CHECK_EQ(r.skipped_lines, size_t{0});
}

TEST("session/accepts_hex_teids_and_comments") {
  const std::string path = write_temp(
      "# generated by tools/gen_traffic.py\n"
      "310150000000003,0x1000,0x2000,5\n"
      "\n");
  const SessionLoadResult r = load_sessions_csv(path);
  std::remove(path.c_str());

  REQUIRE(r.ok());
  REQUIRE_EQ(r.sessions.size(), size_t{1});
  CHECK_EQ(r.sessions[0].ul_teid, 0x1000u);
  CHECK_EQ(r.sessions[0].dl_teid, 0x2000u);
}

TEST("session/skips_malformed_rows_without_failing") {
  const std::string path = write_temp(
      "310150000000004,100,200,1\n"
      "not-a-number,1,2,3\n"
      "310150000000005\n"
      "310150000000006,4294967296,2,3\n"  // TEID out of 32-bit range
      "0,1,2,3\n"                          // IMSI 0 is not a session
      "310150000000007,300,400,2\n");
  const SessionLoadResult r = load_sessions_csv(path);
  std::remove(path.c_str());

  REQUIRE(r.ok());
  CHECK_EQ(r.sessions.size(), size_t{2});
  CHECK_EQ(r.skipped_lines, size_t{4});
}

TEST("session/missing_file_reports_an_error") {
  const SessionLoadResult r = load_sessions_csv("/nonexistent/path/sessions.csv");
  CHECK(!r.ok());
  CHECK(r.sessions.empty());
}

TEST("session/round_trips_through_write") {
  std::vector<SessionSpec> sessions;
  for (uint64_t i = 1; i <= 5; ++i) {
    SessionSpec s;
    s.imsi = 310150000000000ULL + i;
    s.ul_teid = static_cast<uint32_t>(1000 + i);
    s.dl_teid = static_cast<uint32_t>(2000 + i);
    s.rating_group = static_cast<uint32_t>(i);
    s.msisdn = "1555000000" + std::to_string(i);
    s.apn = "internet";
    sessions.push_back(s);
  }
  const std::string path = write_temp("");
  REQUIRE(write_sessions_csv(path, sessions));
  const SessionLoadResult r = load_sessions_csv(path);
  std::remove(path.c_str());

  REQUIRE(r.ok());
  REQUIRE_EQ(r.sessions.size(), sessions.size());
  for (size_t i = 0; i < sessions.size(); ++i) {
    CHECK_EQ(r.sessions[i].imsi, sessions[i].imsi);
    CHECK_EQ(r.sessions[i].ul_teid, sessions[i].ul_teid);
    CHECK_EQ(r.sessions[i].dl_teid, sessions[i].dl_teid);
    CHECK_EQ(r.sessions[i].rating_group, sessions[i].rating_group);
    CHECK_EQ(r.sessions[i].msisdn, sessions[i].msisdn);
  }
}

GTPM_TEST_MAIN()
